import { existsSync, mkdirSync, readFileSync, renameSync } from 'node:fs'
import path from 'node:path'
import { Database } from 'bun:sqlite'
import { drizzle } from 'drizzle-orm/bun-sqlite'
import { migrate } from 'drizzle-orm/bun-sqlite/migrator'
import type { Progress } from '#/lib/types'
import { relations } from './relations'
import { progress, user } from './schema'

export const DATA_DIR = path.resolve(process.env.DATA_DIR ?? path.join(process.cwd(), '../data'))
/** Generated by `bun run db:generate`; the Docker image copies it next to .output/. */
const MIGRATIONS_DIR = path.join(process.cwd(), 'drizzle')

/** Owner of all progress while login is off ("You"); handed to the first admin when it's turned on. */
export const LOCAL_USER_ID = 'local'

mkdirSync(DATA_DIR, { recursive: true })
const sqlite = new Database(path.join(DATA_DIR, 'app.sqlite'))
sqlite.run('PRAGMA journal_mode = WAL')
sqlite.run('PRAGMA foreign_keys = ON')

export const db = drizzle({ client: sqlite, relations })

// Runs on first import. Idempotent, so it's harmless that the Nitro startup plugin and the
// app bundle each get their own copy of this module.
migrate(db, { migrationsFolder: MIGRATIONS_DIR })
ensureLocalUser()
importLegacyProgress()

function ensureLocalUser() {
  db.insert(user)
    .values({
      id: LOCAL_USER_ID,
      name: 'You',
      email: 'you@local.invalid',
      status: 'approved',
      allSeries: true,
    })
    .onConflictDoNothing()
    .run()
}

/** Reading positions used to live in data/progress.json; move them to the local user once. */
function importLegacyProgress() {
  const file = path.join(DATA_DIR, 'progress.json')
  if (!existsSync(file)) return
  let all: Record<string, Progress> = {}
  try {
    all = JSON.parse(readFileSync(file, 'utf8'))
  } catch {
    // unreadable: nothing to import
  }
  db.transaction((tx) => {
    for (const [bookId, p] of Object.entries(all)) {
      if (!Number.isFinite(p?.time)) continue
      tx.insert(progress)
        .values({ userId: LOCAL_USER_ID, bookId, time: p.time, updatedAt: new Date(p.updatedAt ?? Date.now()) })
        .onConflictDoNothing()
        .run()
    }
  })
  renameSync(file, `${file}.imported`)
  console.log(`Imported ${Object.keys(all).length} reading positions from ${file}`)
}
