import { sqliteTable, integer, primaryKey, real, text } from 'drizzle-orm/sqlite-core'
import { sql } from 'drizzle-orm'
import { user } from './auth-schema'

// better-auth's tables (user, session, account, verification), generated by `bun run auth:generate`.
export * from './auth-schema'

/** Series a user may see when `user.allSeries` is false. */
export const userSeries = sqliteTable(
  'user_series',
  {
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    series: text().notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.series] })],
)

/** Reading position per user and book ("<series>/<volume>"). */
export const progress = sqliteTable(
  'progress',
  {
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    bookId: text('book_id').notNull(),
    time: real().notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.bookId] })],
)

/** Emails an admin let in ahead of time: their first Google sign-in is approved right away. */
export const preApprovedEmails = sqliteTable('pre_approved_emails', {
  email: text().primaryKey(),
  addedBy: text('added_by').references(() => user.id, { onDelete: 'set null' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .notNull()
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
})

/** Small key/value store (e.g. the first-admin setup token hash). */
export const meta = sqliteTable('meta', {
  key: text().primaryKey(),
  value: text().notNull(),
})
