/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BooksSeriesVolumeRouteImport } from './routes/books.$series.$volume'
import { Route as ApiProgressSeriesVolumeRouteImport } from './routes/api/progress.$series.$volume'
import { Route as ApiBooksSeriesVolumeAudioRouteImport } from './routes/api/books.$series.$volume.audio'
import { Route as ApiBooksSeriesVolumeCoverRouteImport } from './routes/api/books.$series.$volume.cover'
import { Route as ApiBooksSeriesVolumePdfRouteImport } from './routes/api/books.$series.$volume.pdf'
import { Route as ApiBooksSeriesVolumeWordsRouteImport } from './routes/api/books.$series.$volume.words'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSeriesVolumeRoute = BooksSeriesVolumeRouteImport.update({
  id: '/books/$series/$volume',
  path: '/books/$series/$volume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressSeriesVolumeRoute = ApiProgressSeriesVolumeRouteImport.update({
  id: '/api/progress/$series/$volume',
  path: '/api/progress/$series/$volume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksSeriesVolumeAudioRoute =
  ApiBooksSeriesVolumeAudioRouteImport.update({
    id: '/api/books/$series/$volume/audio',
    path: '/api/books/$series/$volume/audio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBooksSeriesVolumeCoverRoute =
  ApiBooksSeriesVolumeCoverRouteImport.update({
    id: '/api/books/$series/$volume/cover',
    path: '/api/books/$series/$volume/cover',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBooksSeriesVolumePdfRoute = ApiBooksSeriesVolumePdfRouteImport.update({
  id: '/api/books/$series/$volume/pdf',
  path: '/api/books/$series/$volume/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksSeriesVolumeWordsRoute =
  ApiBooksSeriesVolumeWordsRouteImport.update({
    id: '/api/books/$series/$volume/words',
    path: '/api/books/$series/$volume/words',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/books/$series/$volume': typeof BooksSeriesVolumeRoute
  '/api/progress/$series/$volume': typeof ApiProgressSeriesVolumeRoute
  '/api/books/$series/$volume/audio': typeof ApiBooksSeriesVolumeAudioRoute
  '/api/books/$series/$volume/cover': typeof ApiBooksSeriesVolumeCoverRoute
  '/api/books/$series/$volume/pdf': typeof ApiBooksSeriesVolumePdfRoute
  '/api/books/$series/$volume/words': typeof ApiBooksSeriesVolumeWordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/books/$series/$volume': typeof BooksSeriesVolumeRoute
  '/api/progress/$series/$volume': typeof ApiProgressSeriesVolumeRoute
  '/api/books/$series/$volume/audio': typeof ApiBooksSeriesVolumeAudioRoute
  '/api/books/$series/$volume/cover': typeof ApiBooksSeriesVolumeCoverRoute
  '/api/books/$series/$volume/pdf': typeof ApiBooksSeriesVolumePdfRoute
  '/api/books/$series/$volume/words': typeof ApiBooksSeriesVolumeWordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/books/$series/$volume': typeof BooksSeriesVolumeRoute
  '/api/progress/$series/$volume': typeof ApiProgressSeriesVolumeRoute
  '/api/books/$series/$volume/audio': typeof ApiBooksSeriesVolumeAudioRoute
  '/api/books/$series/$volume/cover': typeof ApiBooksSeriesVolumeCoverRoute
  '/api/books/$series/$volume/pdf': typeof ApiBooksSeriesVolumePdfRoute
  '/api/books/$series/$volume/words': typeof ApiBooksSeriesVolumeWordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/books/$series/$volume'
    | '/api/progress/$series/$volume'
    | '/api/books/$series/$volume/audio'
    | '/api/books/$series/$volume/cover'
    | '/api/books/$series/$volume/pdf'
    | '/api/books/$series/$volume/words'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/books/$series/$volume'
    | '/api/progress/$series/$volume'
    | '/api/books/$series/$volume/audio'
    | '/api/books/$series/$volume/cover'
    | '/api/books/$series/$volume/pdf'
    | '/api/books/$series/$volume/words'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/books/$series/$volume'
    | '/api/progress/$series/$volume'
    | '/api/books/$series/$volume/audio'
    | '/api/books/$series/$volume/cover'
    | '/api/books/$series/$volume/pdf'
    | '/api/books/$series/$volume/words'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  BooksSeriesVolumeRoute: typeof BooksSeriesVolumeRoute
  ApiProgressSeriesVolumeRoute: typeof ApiProgressSeriesVolumeRoute
  ApiBooksSeriesVolumeAudioRoute: typeof ApiBooksSeriesVolumeAudioRoute
  ApiBooksSeriesVolumeCoverRoute: typeof ApiBooksSeriesVolumeCoverRoute
  ApiBooksSeriesVolumePdfRoute: typeof ApiBooksSeriesVolumePdfRoute
  ApiBooksSeriesVolumeWordsRoute: typeof ApiBooksSeriesVolumeWordsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$series/$volume': {
      id: '/books/$series/$volume'
      path: '/books/$series/$volume'
      fullPath: '/books/$series/$volume'
      preLoaderRoute: typeof BooksSeriesVolumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress/$series/$volume': {
      id: '/api/progress/$series/$volume'
      path: '/api/progress/$series/$volume'
      fullPath: '/api/progress/$series/$volume'
      preLoaderRoute: typeof ApiProgressSeriesVolumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$series/$volume/audio': {
      id: '/api/books/$series/$volume/audio'
      path: '/api/books/$series/$volume/audio'
      fullPath: '/api/books/$series/$volume/audio'
      preLoaderRoute: typeof ApiBooksSeriesVolumeAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$series/$volume/cover': {
      id: '/api/books/$series/$volume/cover'
      path: '/api/books/$series/$volume/cover'
      fullPath: '/api/books/$series/$volume/cover'
      preLoaderRoute: typeof ApiBooksSeriesVolumeCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$series/$volume/pdf': {
      id: '/api/books/$series/$volume/pdf'
      path: '/api/books/$series/$volume/pdf'
      fullPath: '/api/books/$series/$volume/pdf'
      preLoaderRoute: typeof ApiBooksSeriesVolumePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$series/$volume/words': {
      id: '/api/books/$series/$volume/words'
      path: '/api/books/$series/$volume/words'
      fullPath: '/api/books/$series/$volume/words'
      preLoaderRoute: typeof ApiBooksSeriesVolumeWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  BooksSeriesVolumeRoute: BooksSeriesVolumeRoute,
  ApiProgressSeriesVolumeRoute: ApiProgressSeriesVolumeRoute,
  ApiBooksSeriesVolumeAudioRoute: ApiBooksSeriesVolumeAudioRoute,
  ApiBooksSeriesVolumeCoverRoute: ApiBooksSeriesVolumeCoverRoute,
  ApiBooksSeriesVolumePdfRoute: ApiBooksSeriesVolumePdfRoute,
  ApiBooksSeriesVolumeWordsRoute: ApiBooksSeriesVolumeWordsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
